### ISSUE TITLE
Release binaries are dynamically linked

### ISSUE THREAD

**Issue by ryansch** [CircleCI-Public/circleci-cli#102]
I'm trying to see if I can use this version of the circleci binary to get test parallelization working with remote docker but my default ci container is based on alpine linux.  Go makes it pretty easy to generate a static binary which would make it far more portable.

**Comment by zzak** [comment]
@ryansch Thanks for writing in!

Do you have any recommendation for the best way to do that?

Since we're using `goreleaser` to build the binaries, perhaps we can do it here?
https://github.com/CircleCI-Public/circleci-cli/blob/50bc25cdf8a0cf9e77127fe71e55532a8b016465/.goreleaser.yml#L20

Though, I've also read that `CGO_ENABLED=0` will do the trick (this seems to be what `goreleaser` themselves are doing).

**Comment by ryansch** [comment]
@zzak I'm a golang n00b so I'm probably not the best person to ask!  I checked the result with the `file` command.

**Comment by ryansch** [comment]
https://github.com/goreleaser/goreleaser/issues/225#issuecomment-300794714 seems to indicate that you're right about `CGO_ENABLED=0`

**Comment by salekseev** [comment]
Indeed release binaries are dynamically linked and do not work on musl distributions like alpine:
```
# /usr/bin/circleci
bash: /usr/bin/circleci: No such file or directory
# ldd /usr/bin/circleci
	/lib64/ld-linux-x86-64.so.2 (0x7faa089aa000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7faa089aa000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7faa089aa000)
```
