### ISSUE TITLE
Where is "circleci tests split" command in the new version?

### ISSUE THREAD

**Issue by kvolkovich-sc** [CircleCI-Public/circleci-cli#119]
```
$ circleci version                                                                              
0.1.2347+39dfda0

$ circleci                                                                                      
This project is the seed for CircleCI's new command-line application.

Usage:
  circleci [command]

Available Commands:
  config      Operate on build config files
  diagnostic  Check the status of your CircleCI CLI.
  help        Help about any command
  local       Debug jobs on the local machine
  namespace   Operate on namespaces
  orb         Operate on orbs
  query       Query the CircleCI GraphQL API.
  setup       Setup the CLI with your credentials
  update      Update the tool
  version     Display version information

Flags:
  -h, --help           help for circleci
      --host string    URL to your CircleCI host (default "https://circleci.com")
      --token string   your token for using CircleCI
      --verbose        Enable verbose logging.
Use "circleci [command] --help" for more information about a command.
```

It looks like `circleci tests split` command is missing.

https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-test-files

Did you break support of it?

**Comment by zzak** [comment]
Hello @kvolkovich-sc!

Thank you for your report.

It's still there, we actually proxy this command to the old binary (under the hood) in order to maintain compatibility. We've hidden it from the help because the idea is that this command would only be used within builds.

Are you using this command in your local workflow?

We are trying to make clearer boundary between the CLI you run on your desktop and the agent that executes commands (like `tests split`) within your build.

**Comment by kvolkovich-sc** [comment]
No, I don't use it in my local workflow.

But its confusing.

> We've hidden it from the help because the idea is that this command would only be used within builds.

It looks like we have two different CLI tools with the same name.

But within CircleCI build container `circleci` and `circleci-agent` are the same things.

`diff -a /bin/circleci /bin/circleci-agent // => nothing`

I'm sure that it shouldn't be difference in behavior between local and remote things with the identical name. It should be named differently.

If its just a question of taking short beautiful name for binary (`circleci`), then its strange decision.

**Comment by zzak** [comment]
Thanks for your feedback @kvolkovich-sc.

So I have a clear understanding, it's confusing because the docs mention the command but the help command doesn't?

Inside the build container `circleci` is reserved in order to maintain compatibility with existing build configs, but is the same CLI as the `circleci-agent` executing commands of your build. We want to transition people over to using the agent and use the much shorter (in your words beautiful :) name `circleci` for this CLI which is used for validating build configs, publish and test orbs, and running local jobs, among other things as we continue to add new features to it.

Hope that clears things up, please let me know if you have any other questions!

**Comment by kvolkovich-sc** [comment]
I understand what you do.

If I am the first who ask about it, then maybe it were unclear only for me. But if not, it would be nice if you add these explanations to some README.

Thanks for answer and CircleCI :)
