### ISSUE TITLE
`validate` incorrectly says `config.yml` files with emoji are valid

### ISSUE THREAD

**Issue by glasnt** [CircleCI-Public/circleci-cli#187]
(This is somewhat related to a support request I've already submitted, but thought this would be useful for visibility)

If I have a `.circleci/config.yml` file with an emoji in it, the `circleci config validate` check says it's valid, but it's never picked up by CircleCI, as something is silently failing. 

Emoji may not be supposed by all yaml parsers, for example in Python: 
```
>>> import yaml
>>> with open(".circleci/config.yml") as f:
...     y = yaml.load(f)
...
yaml.reader.ReaderError: unacceptable character #x1f527: special characters are not allowed
```

However, I assume this golang CLI does yaml parsing, and thinks the config is valid. 

Somewhere in the pipeline this is silently failing. That is: the build is **never picked up by CircleCI**

Basic issue reproduction: https://github.com/glasnt/verbose-journey/commits/master (note the change made in f3821380 and how there's no CI status badge on the commit)

I'm not a golang dev, but I'd suggest: 
* upstream investigations, and/or, as a workaround
* make the `validate` fail if emoji are spotted (not a complete workaround, as `validate` doesn't block building, but it might be useful

**Comment by eddiewebb** [comment]
>I'm not a golang dev, but I'd suggest:

* upstream investigations, and/or, as a workaround
* make the `validate` fail if emoji are spotted (not a complete workaround, as `validate` doesn't block building, but it might be useful


The first is being tracked/discussed internally, and as you noted is entirely the fault of yaml parsers within the platform.  We're tracking interest to support emojis here, https://ideas.circleci.com/ideas/CCI-I-741

The second, more applicable to the CLI itself seems viable in the short-term since we know the platform won't handle emojis, it should be possible to run an explicit check for their presence.

I'll label this and see if any golang devs might be willing to contribute something.

**Comment by zzak** [comment]
As it turns out, most of the CLI commands (including `validate`) are simply wrapping HTTP calls to our API that handle the processing of config, etc. We recognize this is an issue and have a card in our backlog to address it in the proper place.

There is also an [Idea post](https://circleci.com/ideas/?idea=CCI-I-741) to gather interest in supporting emojis within the config.
