### ISSUE TITLE
`tests` command not documented on `--help`

### ISSUE THREAD

**Issue by PaulRBerg** [CircleCI-Public/circleci-cli#269]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**

Request a feature, I guess.

**What is the current behavior?**

The `tests` command is not listed when running `circleci --help`.

Can you provide an example?

Run `circleci --help`.

**What is the expected behavior?**

Print documentation for `tests` because it turns out to be an useful feature to set up parallelism on CircleCI.

**Which version of the CLI and OS are you using? Did this work in previous versions?**

Using circleci `0.1.4786+bad101f` and macos `10.14.2`. Not sure if the documentation was printed in previous versions because this is the first time I'm using it.

**Comment by eric-hu** [comment]
Hi @PaulRBerg ! Thanks for taking the time to open this issue!

Documentation for test splitting can be found [in this section of the online docs](https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-the-circleci-cli-to-split-tests). We made a deliberate choice to not show `tests` in the CLI help here. The command exists because there's shared code between the local CLI and the one run inside of a CircleCI job. Even though `circleci test` is useful locally to figure out how to use it inside of your jobs, it doesn't have a standalone local use case. We showed `circleci test` documentation in a different version of the CLI before, and it generated confusion about what it was for.
