### ISSUE TITLE
`circleci orb init` overwrites .gitignore

### ISSUE THREAD

**Issue by seongwon-kang** [CircleCI-Public/circleci-cli#504]
## Meta:

**CircleCI CLI Version:**
0.1.11232+94b7e37 (release)

**Operating System:**
Windows 10 Pro

**CircleCI CLI Diagnostic:**
```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: .circleci\cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
```

---

## Current behavior:

Complete  `circleci orb init .` on repo folder which `.gitinore` exist.
Then `.gitignore` file will be overwritten with 2 line contents.

## Expected behavior:

Just append `orb.yml` to end of `.gitignore` file.

**Comment by gmemstr** [comment]
`orb init` expects to be given a completely new directory, with no contents or existing repository. This is expected behaviour, since we download and extract the latest release of the [Orb Project Template](https://github.com/CircleCI-Public/Orb-Project-Template) and use that as a base to replace values.
