### ISSUE TITLE
Context values no longer verifiable

### ISSUE THREAD

**Issue by rcalosso** [CircleCI-Public/circleci-cli#515]
## Meta:

**CircleCI CLI Version:**
0.1.10656+c7c1710 (release)

**Operating System:**
Mac 10.15.7
**CircleCI CLI Diagnostic:**
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/richardcalosso/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Richard Calosso.

---

## Current behavior:
Context: build
+------------------------------+-------+
|     ENVIRONMENT VARIABLE     | VALUE |
+------------------------------+-------+
| AWS_ACCESS_KEY_ID            | ••••  |
| AWS_ARTIFACTORY_API_KEY      | ••••  |

## Expected behavior:
+--------------------------------------------+----------+
|            ENVIRONMENT VARIABLE            |  VALUE   |
+--------------------------------------------+----------+
| AWS_ACCESS_KEY_ID                          | ••••L5RQ |
| AWS_ARTIFACTORY_API_KEY                    | ••••oSk4 |

## When did this begin / Was this previously working?:
Works fine with 9321, breaks on all versions after

## Additional Information:
I need a way to validate the values either last 4 or sha or checksum.  Any published way to validate contents without revealing the value would be ok.  Need to be able to detect changes and validate values.

**Comment by rcalosso** [comment]
Also reported another anomaly, the broken versions only return first 20 variables

**Comment by johnswanson** [comment]
Hi @rcalosso, thanks for the report. https://github.com/CircleCI-Public/circleci-cli/pull/517 should fix the issue with only the first 20 variables being returned.

Regarding truncated secrets: this is actually behaving as intended right now. I'm sorry about our lack of up-front communication on this, but long story short, we're removing the ability to view the last 4 characters of environment variables due to security concerns.

This is all made more confusing because we've removed that ability in our public, v2 REST API, but it's still present in our deprecated, private graphQL API. So, when we switched the CLI to use the new API, the CLI lost the ability to print the last 4 chars of secrets.

Sometime in the future we are hoping to implement a better solution to allow verifying secrets without posing a security risk (for example, providing a hash of the secret). Would something like that solve your issue?

In the meantime, you can continue to use the old version of the CLI - hopefully we'll have a better answer for your use case soon.
