### ISSUE TITLE
config validate no longer works on snap version

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli#82]
Running `circleci config validate` with the new CLI installed via `snap` no longer works. Returns the error:

> Error: Could not load config file at .circleci/config.yml: open .circleci/config.yml: permission denied

**Comment by felicianotech** [comment]
Someone with the same issue: https://discuss.circleci.com/t/circleci-apparmor-issue-for-validation-on-ubuntu-linux/24411

**Comment by MFProduction** [comment]
+1

**Comment by marcomorain** [comment]
My hunch is that this is caused by our [Snap confinement setting](https://github.com/CircleCI-Public/circleci-cli/blob/66a9073bd8e0e428bf2d62d8ef27cea0737fce80/snapcraft.yaml#L7) being `strict`.

https://docs.snapcraft.io/reference/confinement

> Strict confinement gives you the following readable and/or writable paths:
> 
> - /snap/<snap>/<revision> (read-only, snap install path)
> - /var/snap/<snap>/<revision> (read/write, per-revision data)
> - /var/snap/<snap>/common (read/write, common data)
> - /home/$USER/snap/<snap>/<revision> (read/write, per-revision user data)
> - /home/$USER/snap/<snap>/common (read/write, common user data)

When running the binary through snap, we should be writing settings to `/home/$USER/snap/<snap>/common` I guess.

**Comment by marcomorain** [comment]
If we detect `SNAP_USER_COMMON` at runtime, we should be able to used it as the home directory.

**Comment by felicianotech** [comment]
I have a potential fix for this. Waiting for permissions on this repo so that I can open a PR.
