### ISSUE TITLE
`circleci config validate` failing (`failed to decode body: invalid character 'I'`)

### ISSUE THREAD

**Issue by scottx611x** [CircleCI-Public/circleci-cli#904]
## Meta:

**CircleCI CLI Version:**
Observed on both: 
- `0.1.25725+63309c6 (release)`
- `0.1.25725+63309c6 (homebrew)`

**Operating System:**
-  `Ubuntu 22.04.1 LTS`
- `macOS Monterey 12.6.2 (21G320)`

**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/circleci/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Scott Ouellette.
```

---

## Current behavior:
I've observed this in multiple projects both locally and in CI ssh re-runs 

```
$ circleci config validate
failed to decode body: invalid character 'I' looking for beginning of valueError: config compilation request returned an error: invalid character 'I' looking for beginning of value
```

## Expected behavior:
We should be able to validate our configs

## When did this begin / Was this previously working?:
We observed this behavior just this morning. Notably workflows kicked off using said configs that are failing to validate are working as intended

**Comment by Kylmakalle** [comment]
I can confirm the issue as well. Submitted a support ticket #131260

My investigations revealed that the most recent versions of CLI send YAML to `https://api.circleci.com/api/v2/compile-config-with-defaults` endpoint, which returns 401 `Invalid token provided.` It looks like this endpoint was introduced in https://github.com/CircleCI-Public/circleci-cli/pull/865 and was accidentally secured by some authentication couple of hours ago.

Temporary workarounds
- Do not run `circleci config process` and `circleci config validate` commands
- Switch to the older CLI version, like [v0.1.23845](https://github.com/CircleCI-Public/circleci-cli/releases/tag/v0.1.23845), which uses `https://circleci.com/graphql-unstable` endpoint

**Comment by Kylmakalle** [comment]
I got an update from support. The commands above now work on CircleCI. Unfortunately, they still do not work locally.

**Comment by michaellarocca90** [comment]
We are seeing this on version `0.1.23667` and version `0.1.25725` from docker executors within circleci.

**Comment by michaellarocca90** [comment]
This seems like it should be an incident on CircleCI's end?

**Comment by elliotforbes** [comment]
Howdy folks! 

This issue should now be resolved - the underlying reason why this issue occurred was two-fold:

* We've recently migrated off an unstable graphQL service internally and started communicating directly with `v2` APIs. For historical reasons the `Circle-Token` header was sent as an empty string to this old API endpoint.
* In the past few days, we've been exploring a new API UX improvement wherein we will return 401 unauthorized if an invalid request is sent with _any_ API request. This is a fairly big behavioural change which should help folks investigate and identify why they're not able to make API requests with invalid tokens far quicker so it's a huge win.

This combination then meant that, when the auth changes were rolled out, the CLI was effectively sending an invalid authorization token `""`. 

We've patched this for now and the team that owns this project will be working on a fix for the CLI so that it does the right thing going forward.

Please feel free to reopen this issue should this regression reappear!

**Comment by blimmer** [comment]
@elliotforbes I'm experiencing this issue this morning:

```
> circleci config validate
failed to decode body: invalid character 'I' looking for beginning of valueError: config compilation request returned an error: invalid character 'I' looking for beginning of value
> circleci version
0.1.25725+63309c6 (homebrew)
```

**Comment by elliotforbes** [comment]
@blimmer - Can you confirm if you are running on a server instance of CircleCI and not on the cloud?

If so, you may need to update your version of server such that the API that supports this no longer sends invalid JSON back to the CLI.

**Comment by robotadam** [comment]
> the team that owns this project will be working on a fix for the CLI so that it does the right thing going forward.

Is there an issue we can watch for fixing the CLI? It seems to work with a personal access token set up and linked with `circleci setup`, but we have validate in pre-commit hooks in a few places and I don't want everyone to have to set up a personal access token just for validation.

**Comment by blimmer** [comment]
@elliotforbes this was against CircleCI cloud. It's working now, but definitely was not when I posted.

**Comment by blimmer** [comment]
Actually @elliotforbes this is still failing for me. I tried the following:

```
> brew uninstall circleci
> rm -fr ~/.circleci
> brew install circleci
> circleci setup
CircleCI API Token ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
API token has been set.
CircleCI Host https://circleci.com
CircleCI host has been set.
Setup complete.
Your configuration has been saved to /Users/blimmer/.circleci/cli.yml.

Trying an introspection query on API to verify your setup... Ok.
Trying to query our API for your profile name... Hello!
> circleci config validate
failed to decode body: invalid character 'I' looking for beginning of valueError: config compilation request returned an error: invalid character 'I' looking for beginning of value
```

**Comment by elliotforbes** [comment]
@blimmer - I'll follow up with the team that owns this project and see if they can update it to more gracefully handle non-json errors from the underlying APIs.

The `invalid character 'I'` is referencing the first character in the `Invalid API token` string message that is returned when an API token used is no longer valid, this change was unfortunately something that went live after my own updates which is why the original pull request doesn't handle this as gracefully as it should.

**Comment by tdebarochez** [comment]
@blimmer yes, it seems to be the case.
For the record, before re-running `circleci setup` I had the following error with the latest version of the CLI (`0.1.26255+cc8c4de`):
```
❯ circleci config validate
Error: config compilation request returned an error: %!w(<nil>)
```
